"""
Alert rule model for user-configured alert rules.

Stores alert rule configurations that define when and how
alerts should be triggered for a project.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from semrush_core.models.base import Base, UUIDMixin

if TYPE_CHECKING:
    from semrush_core.models.alert import Alert
    from semrush_core.models.project import Project


class AlertRuleType(str, Enum):
    """Types of alert rules."""

    VISIBILITY_DROP = "visibility_drop"
    CTR_OPPORTUNITY = "ctr_opportunity"
    REGRESSION = "regression"


class AlertRule(Base, UUIDMixin):
    """
    Alert rule model for user-configured alert rules.

    Defines the conditions under which alerts should be triggered
    for a project.

    Attributes:
        project_id: UUID of the parent project.
        rule_type: Type of alert rule.
        config: Rule configuration as JSONB.
        is_enabled: Whether the rule is active.
        created_at: When the rule was created.
        project: Parent project.
        alerts: Alerts generated by this rule.
    """

    __tablename__ = "alert_rules"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    rule_type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    config: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
    )
    is_enabled: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    project: Mapped[Project] = relationship(back_populates="alert_rules")
    alerts: Mapped[list[Alert]] = relationship(
        back_populates="alert_rule",
        lazy="selectin",
    )

    @property
    def is_visibility_drop(self) -> bool:
        """Check if this is a visibility drop rule."""
        return self.rule_type == AlertRuleType.VISIBILITY_DROP.value

    @property
    def is_ctr_opportunity(self) -> bool:
        """Check if this is a CTR opportunity rule."""
        return self.rule_type == AlertRuleType.CTR_OPPORTUNITY.value

    @property
    def is_regression(self) -> bool:
        """Check if this is a regression rule."""
        return self.rule_type == AlertRuleType.REGRESSION.value

    def get_threshold(self, key: str, default: Any = None) -> Any:
        """
        Get a threshold value from the config.

        Args:
            key: Config key to retrieve.
            default: Default value if key not found.

        Returns:
            Threshold value or default.
        """
        return self.config.get(key, default)
